version: "3.7"

services:
  redis:
    image: redis:6.2.5
    command: redis-server --requirepass mxs
    volumes:
      - ./redis:/var/lib/redis
      - ./redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    links:
      - redis-commander

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: mxs
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081

  pgsql:
    image: postgres:12.2
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5010:5432
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80 #http://localhost:5011/browser/
    user: root
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - pgsql:pgsql-server

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672 #http://localhost:15672
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  redis:
  redis-config:
  pgsql-data:
  pgadmin-data: